Feature: add folowup functionality
uqarni/reposite-worker pull request #1
Opened 2023-10-24 15:10 UTC by muizkhan27

2023-10-27 03:13 UTC, uqarni requested changes
looking good, let's address my comments together tomorrow.

2023-10-27 03:13 UTC, uqarni commented on followup.py
> +                llm_sorted_messages.append({'role': 'user', 'content': secret_message})
let's log llm_sorted_messages somewhere for QC for a week or so

2023-10-27 03:13 UTC, uqarni commented on followup.py
> +                        usage = response['usage']
we need to add usage into the tokens columns of messages when we append the outbound message to our DB

2023-10-27 03:13 UTC, uqarni commented on followup_response.py
> +        output = no
lol. ok we should improve these a bit to be more realistic.

2023-10-27 03:13 UTC, uqarni commented on followup_response.py
> +        output = yes
hahaha. let's improve these.

2023-10-27 03:13 UTC, uqarni commented on followup_response.py
> +            error = ''
we actually need also track usage here as well. let's discuss.

2023-10-27 03:13 UTC, uqarni commented on llmwrapper.py
> +            response = openai.ChatCompletion.create(model="gpt-4", temperature = 0, messages=to_summarize, max_tokens=200, user='muiz')
user = 'reposite'

2023-10-27 03:13 UTC, uqarni commented on worker.py
thanks for all this. appreciated.

2023-10-27 03:13 UTC, uqarni commented on worker.py
> +    call_followup()
im confused here. we need to keep the 15-minute responder going. the followup will be deployed separately. it should run once a day.

2023-10-27 14:22 UTC, muizkhan27 commented on followup.py
> +def followup(db):
Yes I ll be doing it in the refactoring part that I am focusing on Today

2023-10-27 14:22 UTC, muizkhan27 commented on followup.py
> +                if ntmcampaignbucket == None:
Yes we can

2023-10-27 14:23 UTC, muizkhan27 commented on followup.py
> +                temp_formatted_system_prompt = system_prompt.format(**prompt_variables)
It was with example as I was testing it and it ll be dry after refactoring

2023-10-27 14:23 UTC, muizkhan27 commented on followup.py
> +                llm_sorted_messages.append({'role': 'user', 'content': secret_message})
Sure, Will be done.

2023-10-27 14:23 UTC, muizkhan27 commented on followup.py
> +                        response = openai.ChatCompletion.create(model="gpt-4", temperature = 0, messages=llm_sorted_messages, max_tokens=600, user='muiz')
Okay, Noted.

2023-10-28 15:33 UTC, muizkhan27 commented on followup.py
> +                if ntmcampaignbucket == None:
Resolved

2023-10-28 15:34 UTC, muizkhan27 commented on followup.py
> +                temp_formatted_system_prompt = system_prompt.format(**prompt_variables)
Resolved

2023-10-28 15:34 UTC, muizkhan27 commented on followup.py
> +                        response = openai.ChatCompletion.create(model="gpt-4", temperature = 0, messages=llm_sorted_messages, max_tokens=600, user='muiz')
Done

2023-10-28 15:35 UTC, muizkhan27 commented on llmwrapper.py
> +            response = openai.ChatCompletion.create(model="gpt-4", temperature = 0, messages=to_summarize, max_tokens=200, user='muiz')
Resolved

2023-10-28 15:35 UTC, muizkhan27 commented on worker.py
Your welcome

2023-10-28 15:38 UTC, muizkhan27 commented on worker.py
> +    call_followup()
I have add another job in the scheduler to run followup every at 6:15 AM.

2023-10-28 15:38 UTC, muizkhan27 commented on worker.py
Resolved

2023-11-02 15:55 UTC, muizkhan27 commented on followup_response.py
> +            error = ''
Its done

2023-11-02 17:22 UTC, merged